//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAF.AgenteServicios.ProxyServicioPropuestaAuditoria {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SP_SAF_MEJOREQUIPO_Result", Namespace="http://schemas.datacontract.org/2004/07/SAF.Entidad")]
    [System.SerializableAttribute()]
    public partial class SP_SAF_MEJOREQUIPO_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CAPAHORAUDFINField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CAPAHORGESPUBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CAPAPUNTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CODAUDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CODCARField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DISPONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> EXPHORAUDFINField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> EXPHORGESPUBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> EXPPUNTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOMCARField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOMCOMAUDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TOTALPUNTField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CAPAHORAUDFIN {
            get {
                return this.CAPAHORAUDFINField;
            }
            set {
                if ((this.CAPAHORAUDFINField.Equals(value) != true)) {
                    this.CAPAHORAUDFINField = value;
                    this.RaisePropertyChanged("CAPAHORAUDFIN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CAPAHORGESPUB {
            get {
                return this.CAPAHORGESPUBField;
            }
            set {
                if ((this.CAPAHORGESPUBField.Equals(value) != true)) {
                    this.CAPAHORGESPUBField = value;
                    this.RaisePropertyChanged("CAPAHORGESPUB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CAPAPUNT {
            get {
                return this.CAPAPUNTField;
            }
            set {
                if ((this.CAPAPUNTField.Equals(value) != true)) {
                    this.CAPAPUNTField = value;
                    this.RaisePropertyChanged("CAPAPUNT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CODAUD {
            get {
                return this.CODAUDField;
            }
            set {
                if ((this.CODAUDField.Equals(value) != true)) {
                    this.CODAUDField = value;
                    this.RaisePropertyChanged("CODAUD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CODCAR {
            get {
                return this.CODCARField;
            }
            set {
                if ((this.CODCARField.Equals(value) != true)) {
                    this.CODCARField = value;
                    this.RaisePropertyChanged("CODCAR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DISPON {
            get {
                return this.DISPONField;
            }
            set {
                if ((this.DISPONField.Equals(value) != true)) {
                    this.DISPONField = value;
                    this.RaisePropertyChanged("DISPON");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> EXPHORAUDFIN {
            get {
                return this.EXPHORAUDFINField;
            }
            set {
                if ((this.EXPHORAUDFINField.Equals(value) != true)) {
                    this.EXPHORAUDFINField = value;
                    this.RaisePropertyChanged("EXPHORAUDFIN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> EXPHORGESPUB {
            get {
                return this.EXPHORGESPUBField;
            }
            set {
                if ((this.EXPHORGESPUBField.Equals(value) != true)) {
                    this.EXPHORGESPUBField = value;
                    this.RaisePropertyChanged("EXPHORGESPUB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> EXPPUNT {
            get {
                return this.EXPPUNTField;
            }
            set {
                if ((this.EXPPUNTField.Equals(value) != true)) {
                    this.EXPPUNTField = value;
                    this.RaisePropertyChanged("EXPPUNT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOMCAR {
            get {
                return this.NOMCARField;
            }
            set {
                if ((object.ReferenceEquals(this.NOMCARField, value) != true)) {
                    this.NOMCARField = value;
                    this.RaisePropertyChanged("NOMCAR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOMCOMAUD {
            get {
                return this.NOMCOMAUDField;
            }
            set {
                if ((object.ReferenceEquals(this.NOMCOMAUDField, value) != true)) {
                    this.NOMCOMAUDField = value;
                    this.RaisePropertyChanged("NOMCOMAUD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TOTALPUNT {
            get {
                return this.TOTALPUNTField;
            }
            set {
                if ((this.TOTALPUNTField.Equals(value) != true)) {
                    this.TOTALPUNTField = value;
                    this.RaisePropertyChanged("TOTALPUNT");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyServicioPropuestaAuditoria.IPropuestaAuditoriaLogic")]
    public interface IPropuestaAuditoriaLogic {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPropuestaAuditoriaLogic/GrabarInvitacion", ReplyAction="http://tempuri.org/IPropuestaAuditoriaLogic/GrabarInvitacionResponse")]
        SAF.DTO.InvitacionDTO GrabarInvitacion(SAF.DTO.InvitacionDTO entidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPropuestaAuditoriaLogic/GrabarInvitacion", ReplyAction="http://tempuri.org/IPropuestaAuditoriaLogic/GrabarInvitacionResponse")]
        System.Threading.Tasks.Task<SAF.DTO.InvitacionDTO> GrabarInvitacionAsync(SAF.DTO.InvitacionDTO entidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPropuestaAuditoriaLogic/ListarInvitacion", ReplyAction="http://tempuri.org/IPropuestaAuditoriaLogic/ListarInvitacionResponse")]
        SAF.DTO.InvitacionViewDTO[] ListarInvitacion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPropuestaAuditoriaLogic/ListarInvitacion", ReplyAction="http://tempuri.org/IPropuestaAuditoriaLogic/ListarInvitacionResponse")]
        System.Threading.Tasks.Task<SAF.DTO.InvitacionViewDTO[]> ListarInvitacionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPropuestaAuditoriaLogic/VerMejorEquipoAuditoria", ReplyAction="http://tempuri.org/IPropuestaAuditoriaLogic/VerMejorEquipoAuditoriaResponse")]
        SAF.AgenteServicios.ProxyServicioPropuestaAuditoria.SP_SAF_MEJOREQUIPO_Result[] VerMejorEquipoAuditoria(int idPublicacion, int idServicioAud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPropuestaAuditoriaLogic/VerMejorEquipoAuditoria", ReplyAction="http://tempuri.org/IPropuestaAuditoriaLogic/VerMejorEquipoAuditoriaResponse")]
        System.Threading.Tasks.Task<SAF.AgenteServicios.ProxyServicioPropuestaAuditoria.SP_SAF_MEJOREQUIPO_Result[]> VerMejorEquipoAuditoriaAsync(int idPublicacion, int idServicioAud);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPropuestaAuditoriaLogicChannel : SAF.AgenteServicios.ProxyServicioPropuestaAuditoria.IPropuestaAuditoriaLogic, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PropuestaAuditoriaLogicClient : System.ServiceModel.ClientBase<SAF.AgenteServicios.ProxyServicioPropuestaAuditoria.IPropuestaAuditoriaLogic>, SAF.AgenteServicios.ProxyServicioPropuestaAuditoria.IPropuestaAuditoriaLogic {
        
        public PropuestaAuditoriaLogicClient() {
        }
        
        public PropuestaAuditoriaLogicClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PropuestaAuditoriaLogicClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PropuestaAuditoriaLogicClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PropuestaAuditoriaLogicClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SAF.DTO.InvitacionDTO GrabarInvitacion(SAF.DTO.InvitacionDTO entidad) {
            return base.Channel.GrabarInvitacion(entidad);
        }
        
        public System.Threading.Tasks.Task<SAF.DTO.InvitacionDTO> GrabarInvitacionAsync(SAF.DTO.InvitacionDTO entidad) {
            return base.Channel.GrabarInvitacionAsync(entidad);
        }
        
        public SAF.DTO.InvitacionViewDTO[] ListarInvitacion() {
            return base.Channel.ListarInvitacion();
        }
        
        public System.Threading.Tasks.Task<SAF.DTO.InvitacionViewDTO[]> ListarInvitacionAsync() {
            return base.Channel.ListarInvitacionAsync();
        }
        
        public SAF.AgenteServicios.ProxyServicioPropuestaAuditoria.SP_SAF_MEJOREQUIPO_Result[] VerMejorEquipoAuditoria(int idPublicacion, int idServicioAud) {
            return base.Channel.VerMejorEquipoAuditoria(idPublicacion, idServicioAud);
        }
        
        public System.Threading.Tasks.Task<SAF.AgenteServicios.ProxyServicioPropuestaAuditoria.SP_SAF_MEJOREQUIPO_Result[]> VerMejorEquipoAuditoriaAsync(int idPublicacion, int idServicioAud) {
            return base.Channel.VerMejorEquipoAuditoriaAsync(idPublicacion, idServicioAud);
        }
    }
}
