//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAF.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAF_DIALABORABLE
    {
        public int CODDIL { get; set; }
        public Nullable<System.DateTime> FECDIL { get; set; }
        public Nullable<int> DIADIL { get; set; }
        public Nullable<int> MESDIL { get; set; }
        public Nullable<int> ANIODIL { get; set; }
        public Nullable<System.DateTime> FECREG { get; set; }
        public Nullable<System.DateTime> FECMOD { get; set; }
        public string USUREG { get; set; }
        public string USUMOD { get; set; }
        public string ESTREG { get; set; }
    }
}
