//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAF.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAF_SOLEXPERIENCIA
    {
        public int CODSOLEXP { get; set; }
        public string DESSOLEXP { get; set; }
        public Nullable<int> TIPEMPSOLEXP { get; set; }
        public Nullable<System.DateTime> FECINISOLEXP { get; set; }
        public Nullable<System.DateTime> FECFINSOLEXP { get; set; }
        public Nullable<int> NUMHORSOLEXP { get; set; }
        public Nullable<System.DateTime> FECREG { get; set; }
        public Nullable<System.DateTime> FECMOD { get; set; }
        public string USUREG { get; set; }
        public string USUMOD { get; set; }
        public string ESTREG { get; set; }
        public Nullable<int> CODSOL { get; set; }
        public Nullable<int> CODEMP { get; set; }
    
        public virtual SAF_EMPRESA SAF_EMPRESA { get; set; }
        public virtual SAF_SOLICITUD SAF_SOLICITUD { get; set; }
    }
}
