//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAF.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAF_TIPOSOLICITUD
    {
        public SAF_TIPOSOLICITUD()
        {
            this.SAF_SOLICITUD = new HashSet<SAF_SOLICITUD>();
        }
    
        public int CODTIPSOL { get; set; }
        public string NOMTIPSOL { get; set; }
        public string DESTIPSOL { get; set; }
        public Nullable<System.DateTime> FECREG { get; set; }
        public Nullable<System.DateTime> FECMOD { get; set; }
        public string USUREG { get; set; }
        public string USUMOD { get; set; }
        public string ESTREG { get; set; }
    
        public virtual ICollection<SAF_SOLICITUD> SAF_SOLICITUD { get; set; }
    }
}
