//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAF.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_SAF_AUDITORIAEQUIPO
    {
        public int CODPROEQU { get; set; }
        public Nullable<int> CODAUD { get; set; }
        public Nullable<int> CODCAR { get; set; }
        public Nullable<int> CODAUDITORIA { get; set; }
        public string NOMCOMAUD { get; set; }
        public string NOMCAR { get; set; }
    }
}
