//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAF.Web.Intranet
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAF_AUDITOR
    {
        public SAF_AUDITOR()
        {
            this.SAF_DIAOCUPADO = new HashSet<SAF_DIAOCUPADO>();
            this.SAF_SOLICITUD = new HashSet<SAF_SOLICITUD>();
            this.SAF_INVITACION = new HashSet<SAF_INVITACION>();
            this.SAF_CORTE_AUDITOR = new HashSet<SAF_CORTE_AUDITOR>();
            this.SAF_CORTE_AUDITOR_CARGO = new HashSet<SAF_CORTE_AUDITOR_CARGO>();
            this.SAF_EXPERIENCIA = new HashSet<SAF_EXPERIENCIA>();
            this.SAF_CAPACITACION = new HashSet<SAF_CAPACITACION>();
        }
    
        public int CODAUD { get; set; }
        public string NOMAUD { get; set; }
        public string APEAUD { get; set; }
        public string DNIAUD { get; set; }
        public string CELAUD { get; set; }
        public string TELAUD { get; set; }
        public string DIRAUD { get; set; }
        public Nullable<int> CODDEPAUD { get; set; }
        public Nullable<int> CODPROVAUD { get; set; }
        public Nullable<int> CODDISAUD { get; set; }
        public string CORAUD { get; set; }
        public string SEXAUD { get; set; }
        public Nullable<System.DateTime> FECNACAUD { get; set; }
        public string INDAUDAUD { get; set; }
        public string INDESPAUD { get; set; }
        public string INDSOCAUD { get; set; }
        public string CODCERAUD { get; set; }
        public byte[] ARCCERAUD { get; set; }
        public Nullable<System.DateTime> FECREG { get; set; }
        public Nullable<System.DateTime> FECMOD { get; set; }
        public string USUREG { get; set; }
        public string USUMOD { get; set; }
        public string ESTREG { get; set; }
        public string NOMUSU { get; set; }
        public string PASUSU { get; set; }
        public Nullable<long> CODARC { get; set; }
        public string NOMBLABEL { get; set; }
    
        public virtual ICollection<SAF_DIAOCUPADO> SAF_DIAOCUPADO { get; set; }
        public virtual ICollection<SAF_SOLICITUD> SAF_SOLICITUD { get; set; }
        public virtual ICollection<SAF_INVITACION> SAF_INVITACION { get; set; }
        public virtual ICollection<SAF_CORTE_AUDITOR> SAF_CORTE_AUDITOR { get; set; }
        public virtual ICollection<SAF_CORTE_AUDITOR_CARGO> SAF_CORTE_AUDITOR_CARGO { get; set; }
        public virtual ICollection<SAF_EXPERIENCIA> SAF_EXPERIENCIA { get; set; }
        public virtual ICollection<SAF_CAPACITACION> SAF_CAPACITACION { get; set; }
    }
}
