//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAF.Web.Intranet
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAF_BASE
    {
        public SAF_BASE()
        {
            this.SAF_SERVICIOAUDITORIA = new HashSet<SAF_SERVICIOAUDITORIA>();
            this.SAF_BASEENTREGABLE = new HashSet<SAF_BASEENTREGABLE>();
            this.SAF_PUBLICACION = new HashSet<SAF_PUBLICACION>();
        }
    
        public int CODBAS { get; set; }
        public Nullable<System.DateTime> FECMAXCREPUBBAS { get; set; }
        public string DESBAS { get; set; }
        public string NUMBAS { get; set; }
        public Nullable<decimal> TOTRETECOBAS { get; set; }
        public Nullable<decimal> TOTVIABAS { get; set; }
        public string FIRPCAOBBAS { get; set; }
        public string FIRINTBAS { get; set; }
        public Nullable<decimal> TOTIGVBAS { get; set; }
        public Nullable<System.DateTime> FECREG { get; set; }
        public Nullable<System.DateTime> FECMOD { get; set; }
        public string USUREG { get; set; }
        public string USUMOD { get; set; }
        public string ESTREG { get; set; }
        public Nullable<int> CODCROENT { get; set; }
        public Nullable<int> ESTBAS { get; set; }
    
        public virtual SAF_CRONOENTIDAD SAF_CRONOENTIDAD { get; set; }
        public virtual ICollection<SAF_SERVICIOAUDITORIA> SAF_SERVICIOAUDITORIA { get; set; }
        public virtual ICollection<SAF_BASEENTREGABLE> SAF_BASEENTREGABLE { get; set; }
        public virtual ICollection<SAF_PUBLICACION> SAF_PUBLICACION { get; set; }
    }
}
