//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAF.Web.Intranet
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAF_EXPERIENCIA
    {
        public int CODEXP { get; set; }
        public string DESEXP { get; set; }
        public Nullable<System.DateTime> FECINIEXP { get; set; }
        public Nullable<System.DateTime> FECFINEXP { get; set; }
        public Nullable<int> NUMHOREXP { get; set; }
        public Nullable<System.DateTime> FECREG { get; set; }
        public Nullable<System.DateTime> FECMOD { get; set; }
        public string USUREG { get; set; }
        public string USUMOD { get; set; }
        public string ESTREG { get; set; }
        public Nullable<int> CODAUD { get; set; }
        public Nullable<int> CODEMP { get; set; }
        public Nullable<int> CODTIPEXP { get; set; }
        public Nullable<long> CODARC { get; set; }
        public string NOMBLABEL { get; set; }
    
        public virtual SAF_AUDITOR SAF_AUDITOR { get; set; }
        public virtual SAF_EMPRESA SAF_EMPRESA { get; set; }
        public virtual SAF_PARAMETRICA SAF_PARAMETRICA { get; set; }
        public virtual SAF_ARCHIVO SAF_ARCHIVO { get; set; }
    }
}
