//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAF.Web.Intranet
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAF_NOTIFICACION
    {
        public int CODNOT { get; set; }
        public string USUNOTREC { get; set; }
        public string DESNOT { get; set; }
        public string INDLEIDO { get; set; }
        public Nullable<System.DateTime> FECREG { get; set; }
        public Nullable<System.DateTime> FECMOD { get; set; }
        public string USUREG { get; set; }
        public string USUMOD { get; set; }
        public string ESTREG { get; set; }
        public string USUEMI { get; set; }
        public string USUREC { get; set; }
        public string ASUNOT { get; set; }
        public string INDNOT { get; set; }
        public string ESTNOT { get; set; }
    }
}
