//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAF.Web.Intranet
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAF_SERAUDCARGO
    {
        public SAF_SERAUDCARGO()
        {
            this.SAF_SERAUDCARCAP = new HashSet<SAF_SERAUDCARCAP>();
            this.SAF_SERAUDCAREXP = new HashSet<SAF_SERAUDCAREXP>();
        }
    
        public int CODSERAUDCAR { get; set; }
        public Nullable<int> NUMMININTSERAUDCAR { get; set; }
        public Nullable<int> NUMMINHORPARSERAUDCAR { get; set; }
        public Nullable<System.DateTime> FECREG { get; set; }
        public Nullable<System.DateTime> FECMOD { get; set; }
        public string USUREG { get; set; }
        public string USUMOD { get; set; }
        public string ESTREG { get; set; }
        public Nullable<int> CODSERAUD { get; set; }
        public Nullable<int> CODCAR { get; set; }
    
        public virtual SAF_CARGO SAF_CARGO { get; set; }
        public virtual ICollection<SAF_SERAUDCARCAP> SAF_SERAUDCARCAP { get; set; }
        public virtual ICollection<SAF_SERAUDCAREXP> SAF_SERAUDCAREXP { get; set; }
        public virtual SAF_SERVICIOAUDITORIA SAF_SERVICIOAUDITORIA { get; set; }
    }
}
