//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAF.Web.Intranet
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_SAF_INVITACION
    {
        public int CODINV { get; set; }
        public Nullable<int> ESTINV { get; set; }
        public string VALOR { get; set; }
        public string FECACEPINV { get; set; }
        public string FECMAXPREPROINV { get; set; }
        public string NUMINV { get; set; }
        public Nullable<int> CODPUB { get; set; }
        public Nullable<int> CODSERAUD { get; set; }
        public int CODAUD { get; set; }
        public string NOMCOMAUD { get; set; }
        public string DNIAUD { get; set; }
        public int CODSOA { get; set; }
        public string RAZSOCSOA { get; set; }
    }
}
