USE [SI_SOCAUD]
GO
DROP TABLE [SAF_NOTIFICACION]
GO
CREATE TABLE [dbo].[SAF_NOTIFICACION](
	[CODNOT] [int] IDENTITY(1,1) NOT NULL,
	[USUEMI] [varchar](50) NULL,
	[USUREC] [varchar](50) NULL,
	[ASUNOT] [varchar](200) NULL,
	[DESNOT] [varchar](max) NULL,
	[INDNOT] [char](1) NULL,
	[ESTNOT] [char](1) NULL,
	[FECREG] [datetime] NULL,
	[FECMOD] [datetime] NULL,
	[USUREG] [varchar](50) NULL,
	[USUMOD] [varchar](50) NULL,
	[ESTREG] [char](1) NULL,
 CONSTRAINT [XPKSAF_NOTIFICACION] PRIMARY KEY CLUSTERED 
(
	[CODNOT] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
