//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAF.Web
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ModeloExtranet : DbContext
    {
        public ModeloExtranet()
            : base("name=ModeloExtranet")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SAF_AUDITOR> SAF_AUDITOR { get; set; }
        public virtual DbSet<SAF_AUDITORIA> SAF_AUDITORIA { get; set; }
        public virtual DbSet<SAF_BASE> SAF_BASE { get; set; }
        public virtual DbSet<SAF_BASEENTREGABLE> SAF_BASEENTREGABLE { get; set; }
        public virtual DbSet<SAF_CARGO> SAF_CARGO { get; set; }
        public virtual DbSet<SAF_CARRERA> SAF_CARRERA { get; set; }
        public virtual DbSet<SAF_CONSULTA> SAF_CONSULTA { get; set; }
        public virtual DbSet<SAF_CORTE_AUDITOR> SAF_CORTE_AUDITOR { get; set; }
        public virtual DbSet<SAF_CORTE_AUDITOR_CARGO> SAF_CORTE_AUDITOR_CARGO { get; set; }
        public virtual DbSet<SAF_CRONOENTIDAD> SAF_CRONOENTIDAD { get; set; }
        public virtual DbSet<SAF_CRONOGRAMA> SAF_CRONOGRAMA { get; set; }
        public virtual DbSet<SAF_DIAOCUPADO> SAF_DIAOCUPADO { get; set; }
        public virtual DbSet<SAF_DOCUMENTO> SAF_DOCUMENTO { get; set; }
        public virtual DbSet<SAF_EMPRESA> SAF_EMPRESA { get; set; }
        public virtual DbSet<SAF_ENTIDADES> SAF_ENTIDADES { get; set; }
        public virtual DbSet<SAF_FLUJO_DOCUMENTO> SAF_FLUJO_DOCUMENTO { get; set; }
        public virtual DbSet<SAF_INVITACION> SAF_INVITACION { get; set; }
        public virtual DbSet<SAF_INVITACIONDETALLE> SAF_INVITACIONDETALLE { get; set; }
        public virtual DbSet<SAF_PARAMETRICA> SAF_PARAMETRICA { get; set; }
        public virtual DbSet<SAF_PROPUESTA> SAF_PROPUESTA { get; set; }
        public virtual DbSet<SAF_PUBLICACION> SAF_PUBLICACION { get; set; }
        public virtual DbSet<SAF_SERAUDCARCAP> SAF_SERAUDCARCAP { get; set; }
        public virtual DbSet<SAF_SERAUDCAREXP> SAF_SERAUDCAREXP { get; set; }
        public virtual DbSet<SAF_SERAUDCARGO> SAF_SERAUDCARGO { get; set; }
        public virtual DbSet<SAF_SERVICIOAUDITORIA> SAF_SERVICIOAUDITORIA { get; set; }
        public virtual DbSet<SAF_SOA> SAF_SOA { get; set; }
        public virtual DbSet<SAF_TIPOPARAMETRICA> SAF_TIPOPARAMETRICA { get; set; }
        public virtual DbSet<SAF_TIPOSOLICITUD> SAF_TIPOSOLICITUD { get; set; }
        public virtual DbSet<SAF_UNIVERSIDAD> SAF_UNIVERSIDAD { get; set; }
        public virtual DbSet<SAF_USUARIO> SAF_USUARIO { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<SAF_DIALABORABLE> SAF_DIALABORABLE { get; set; }
        public virtual DbSet<VW_SAF_INVITACION> VW_SAF_INVITACION { get; set; }
        public virtual DbSet<VW_SAF_PUBLICACION> VW_SAF_PUBLICACION { get; set; }
        public virtual DbSet<VW_SAF_SOLICITUD> VW_SAF_SOLICITUD { get; set; }
        public virtual DbSet<SAF_SOLICITUD> SAF_SOLICITUD { get; set; }
        public virtual DbSet<SAF_DEPARTAMENTO> SAF_DEPARTAMENTO { get; set; }
        public virtual DbSet<SAF_DISTRITO> SAF_DISTRITO { get; set; }
        public virtual DbSet<SAF_PROVINCIA> SAF_PROVINCIA { get; set; }
        public virtual DbSet<SAF_ARCHIVO> SAF_ARCHIVO { get; set; }
        public virtual DbSet<SAF_CAPACITACION> SAF_CAPACITACION { get; set; }
        public virtual DbSet<SAF_EXPERIENCIA> SAF_EXPERIENCIA { get; set; }
        public virtual DbSet<SAF_SOLCAPACITACION> SAF_SOLCAPACITACION { get; set; }
        public virtual DbSet<SAF_SOLEXPERIENCIA> SAF_SOLEXPERIENCIA { get; set; }
        public virtual DbSet<SAF_PROPEQUIPO> SAF_PROPEQUIPO { get; set; }
        public virtual DbSet<SAF_PROPEQUIPODETALLE> SAF_PROPEQUIPODETALLE { get; set; }
        public virtual DbSet<SAF_NOTIFICACION> SAF_NOTIFICACION { get; set; }
    
        public virtual int SP_CARGARDIALABORABLE(string aNIO)
        {
            var aNIOParameter = aNIO != null ?
                new ObjectParameter("ANIO", aNIO) :
                new ObjectParameter("ANIO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CARGARDIALABORABLE", aNIOParameter);
        }
    
        public virtual ObjectResult<SP_SAF_AUDITORAPTOINVITAR_Result> SP_SAF_AUDITORAPTOINVITAR(Nullable<int> cODPUB, Nullable<int> cODSERAUD)
        {
            var cODPUBParameter = cODPUB.HasValue ?
                new ObjectParameter("CODPUB", cODPUB) :
                new ObjectParameter("CODPUB", typeof(int));
    
            var cODSERAUDParameter = cODSERAUD.HasValue ?
                new ObjectParameter("CODSERAUD", cODSERAUD) :
                new ObjectParameter("CODSERAUD", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SAF_AUDITORAPTOINVITAR_Result>("SP_SAF_AUDITORAPTOINVITAR", cODPUBParameter, cODSERAUDParameter);
        }
    
        public virtual ObjectResult<SP_SAF_CORTEPUBLICACION_Result> SP_SAF_CORTEPUBLICACION(Nullable<int> cODPUB)
        {
            var cODPUBParameter = cODPUB.HasValue ?
                new ObjectParameter("CODPUB", cODPUB) :
                new ObjectParameter("CODPUB", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SAF_CORTEPUBLICACION_Result>("SP_SAF_CORTEPUBLICACION", cODPUBParameter);
        }
    
        public virtual ObjectResult<SP_SAF_MEJOREQUIPO_Result> SP_SAF_MEJOREQUIPO(Nullable<int> cODPUB, Nullable<int> cODSERAUD)
        {
            var cODPUBParameter = cODPUB.HasValue ?
                new ObjectParameter("CODPUB", cODPUB) :
                new ObjectParameter("CODPUB", typeof(int));
    
            var cODSERAUDParameter = cODSERAUD.HasValue ?
                new ObjectParameter("CODSERAUD", cODSERAUD) :
                new ObjectParameter("CODSERAUD", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SAF_MEJOREQUIPO_Result>("SP_SAF_MEJOREQUIPO", cODPUBParameter, cODSERAUDParameter);
        }
    
        public virtual ObjectResult<SP_SAF_RESULTADOCORTE_Result> SP_SAF_RESULTADOCORTE(Nullable<int> cODPUB)
        {
            var cODPUBParameter = cODPUB.HasValue ?
                new ObjectParameter("CODPUB", cODPUB) :
                new ObjectParameter("CODPUB", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SAF_RESULTADOCORTE_Result>("SP_SAF_RESULTADOCORTE", cODPUBParameter);
        }
    
        public virtual ObjectResult<SP_SAF_INVITARAUDITORES_Result> SP_SAF_INVITARAUDITORES(Nullable<int> cODSOA, Nullable<int> cODPUB, Nullable<int> cODSERAUD, string sTRAUDITORCARGO)
        {
            var cODSOAParameter = cODSOA.HasValue ?
                new ObjectParameter("CODSOA", cODSOA) :
                new ObjectParameter("CODSOA", typeof(int));
    
            var cODPUBParameter = cODPUB.HasValue ?
                new ObjectParameter("CODPUB", cODPUB) :
                new ObjectParameter("CODPUB", typeof(int));
    
            var cODSERAUDParameter = cODSERAUD.HasValue ?
                new ObjectParameter("CODSERAUD", cODSERAUD) :
                new ObjectParameter("CODSERAUD", typeof(int));
    
            var sTRAUDITORCARGOParameter = sTRAUDITORCARGO != null ?
                new ObjectParameter("STRAUDITORCARGO", sTRAUDITORCARGO) :
                new ObjectParameter("STRAUDITORCARGO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SAF_INVITARAUDITORES_Result>("SP_SAF_INVITARAUDITORES", cODSOAParameter, cODPUBParameter, cODSERAUDParameter, sTRAUDITORCARGOParameter);
        }
    
        public virtual ObjectResult<SP_SAF_INVITACION_Result> SP_SAF_INVITACION(Nullable<int> cODPUB, Nullable<int> cODSERAUD)
        {
            var cODPUBParameter = cODPUB.HasValue ?
                new ObjectParameter("CODPUB", cODPUB) :
                new ObjectParameter("CODPUB", typeof(int));
    
            var cODSERAUDParameter = cODSERAUD.HasValue ?
                new ObjectParameter("CODSERAUD", cODSERAUD) :
                new ObjectParameter("CODSERAUD", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SAF_INVITACION_Result>("SP_SAF_INVITACION", cODPUBParameter, cODSERAUDParameter);
        }
    
        public virtual ObjectResult<SP_SAF_AGENDAREGISTRAR_Result> SP_SAF_AGENDAREGISTRAR(Nullable<int> cODINV, Nullable<int> nUMHOR, string sTRFECHAS)
        {
            var cODINVParameter = cODINV.HasValue ?
                new ObjectParameter("CODINV", cODINV) :
                new ObjectParameter("CODINV", typeof(int));
    
            var nUMHORParameter = nUMHOR.HasValue ?
                new ObjectParameter("NUMHOR", nUMHOR) :
                new ObjectParameter("NUMHOR", typeof(int));
    
            var sTRFECHASParameter = sTRFECHAS != null ?
                new ObjectParameter("STRFECHAS", sTRFECHAS) :
                new ObjectParameter("STRFECHAS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SAF_AGENDAREGISTRAR_Result>("SP_SAF_AGENDAREGISTRAR", cODINVParameter, nUMHORParameter, sTRFECHASParameter);
        }
    
        public virtual ObjectResult<SP_SAF_CREARSOLICITUDAUDITOR_Result> SP_SAF_CREARSOLICITUDAUDITOR(Nullable<int> cODAUD)
        {
            var cODAUDParameter = cODAUD.HasValue ?
                new ObjectParameter("CODAUD", cODAUD) :
                new ObjectParameter("CODAUD", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SAF_CREARSOLICITUDAUDITOR_Result>("SP_SAF_CREARSOLICITUDAUDITOR", cODAUDParameter);
        }
    
        public virtual ObjectResult<SP_SAF_CREARSOLICITUDSOA_Result> SP_SAF_CREARSOLICITUDSOA(Nullable<int> cODSOA)
        {
            var cODSOAParameter = cODSOA.HasValue ?
                new ObjectParameter("CODSOA", cODSOA) :
                new ObjectParameter("CODSOA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SAF_CREARSOLICITUDSOA_Result>("SP_SAF_CREARSOLICITUDSOA", cODSOAParameter);
        }
    
        public virtual ObjectResult<SP_DISPONIBILIDADAUDITOR_Result> SP_DISPONIBILIDADAUDITOR(Nullable<int> cODAUD, Nullable<int> cODSOA, string fECINI, string fECFIN)
        {
            var cODAUDParameter = cODAUD.HasValue ?
                new ObjectParameter("CODAUD", cODAUD) :
                new ObjectParameter("CODAUD", typeof(int));
    
            var cODSOAParameter = cODSOA.HasValue ?
                new ObjectParameter("CODSOA", cODSOA) :
                new ObjectParameter("CODSOA", typeof(int));
    
            var fECINIParameter = fECINI != null ?
                new ObjectParameter("FECINI", fECINI) :
                new ObjectParameter("FECINI", typeof(string));
    
            var fECFINParameter = fECFIN != null ?
                new ObjectParameter("FECFIN", fECFIN) :
                new ObjectParameter("FECFIN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DISPONIBILIDADAUDITOR_Result>("SP_DISPONIBILIDADAUDITOR", cODAUDParameter, cODSOAParameter, fECINIParameter, fECFINParameter);
        }
    
        public virtual ObjectResult<SP_SAF_CREARPROPUESTA_Result> SP_SAF_CREARPROPUESTA(Nullable<int> cODPUB, Nullable<int> cODSOA)
        {
            var cODPUBParameter = cODPUB.HasValue ?
                new ObjectParameter("CODPUB", cODPUB) :
                new ObjectParameter("CODPUB", typeof(int));
    
            var cODSOAParameter = cODSOA.HasValue ?
                new ObjectParameter("CODSOA", cODSOA) :
                new ObjectParameter("CODSOA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SAF_CREARPROPUESTA_Result>("SP_SAF_CREARPROPUESTA", cODPUBParameter, cODSOAParameter);
        }
    
        public virtual ObjectResult<SP_SAF_PROPUESTAS_Result> SP_SAF_PROPUESTAS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SAF_PROPUESTAS_Result>("SP_SAF_PROPUESTAS");
        }
    
        public virtual ObjectResult<SP_SAF_AUDITORIAS_Result> SP_SAF_AUDITORIAS(Nullable<int> cODPRO)
        {
            var cODPROParameter = cODPRO.HasValue ?
                new ObjectParameter("CODPRO", cODPRO) :
                new ObjectParameter("CODPRO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SAF_AUDITORIAS_Result>("SP_SAF_AUDITORIAS", cODPROParameter);
        }
    
        public virtual ObjectResult<SP_SAF_EQUIPOAUDITORIA_Result> SP_SAF_EQUIPOAUDITORIA(Nullable<int> cODAUDITORIA)
        {
            var cODAUDITORIAParameter = cODAUDITORIA.HasValue ?
                new ObjectParameter("CODAUDITORIA", cODAUDITORIA) :
                new ObjectParameter("CODAUDITORIA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SAF_EQUIPOAUDITORIA_Result>("SP_SAF_EQUIPOAUDITORIA", cODAUDITORIAParameter);
        }
    
        public virtual ObjectResult<SP_SAF_ASIGNARFECHASPROPUESTA_Result> SP_SAF_ASIGNARFECHASPROPUESTA(Nullable<int> cODPROEQU, string sTRFECHASASIGNAR)
        {
            var cODPROEQUParameter = cODPROEQU.HasValue ?
                new ObjectParameter("CODPROEQU", cODPROEQU) :
                new ObjectParameter("CODPROEQU", typeof(int));
    
            var sTRFECHASASIGNARParameter = sTRFECHASASIGNAR != null ?
                new ObjectParameter("STRFECHASASIGNAR", sTRFECHASASIGNAR) :
                new ObjectParameter("STRFECHASASIGNAR", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SAF_ASIGNARFECHASPROPUESTA_Result>("SP_SAF_ASIGNARFECHASPROPUESTA", cODPROEQUParameter, sTRFECHASASIGNARParameter);
        }
    
        public virtual ObjectResult<SP_SAF_ELIMINARFECHASASIGPROP_Result> SP_SAF_ELIMINARFECHASASIGPROP(Nullable<int> cODPRO, string sTRCODPROEQUDET)
        {
            var cODPROParameter = cODPRO.HasValue ?
                new ObjectParameter("CODPRO", cODPRO) :
                new ObjectParameter("CODPRO", typeof(int));
    
            var sTRCODPROEQUDETParameter = sTRCODPROEQUDET != null ?
                new ObjectParameter("STRCODPROEQUDET", sTRCODPROEQUDET) :
                new ObjectParameter("STRCODPROEQUDET", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SAF_ELIMINARFECHASASIGPROP_Result>("SP_SAF_ELIMINARFECHASASIGPROP", cODPROParameter, sTRCODPROEQUDETParameter);
        }
    
        public virtual ObjectResult<SP_SAF_FECHASINVITADAS_Result> SP_SAF_FECHASINVITADAS(Nullable<int> cODPROEQU)
        {
            var cODPROEQUParameter = cODPROEQU.HasValue ?
                new ObjectParameter("CODPROEQU", cODPROEQU) :
                new ObjectParameter("CODPROEQU", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SAF_FECHASINVITADAS_Result>("SP_SAF_FECHASINVITADAS", cODPROEQUParameter);
        }
    
        public virtual ObjectResult<SP_SAF_ELIMINARFECHASASIGINVITACION_Result> SP_SAF_ELIMINARFECHASASIGINVITACION(Nullable<int> cODINV, string sTRCODINVDET)
        {
            var cODINVParameter = cODINV.HasValue ?
                new ObjectParameter("CODINV", cODINV) :
                new ObjectParameter("CODINV", typeof(int));
    
            var sTRCODINVDETParameter = sTRCODINVDET != null ?
                new ObjectParameter("STRCODINVDET", sTRCODINVDET) :
                new ObjectParameter("STRCODINVDET", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SAF_ELIMINARFECHASASIGINVITACION_Result>("SP_SAF_ELIMINARFECHASASIGINVITACION", cODINVParameter, sTRCODINVDETParameter);
        }
    }
}
