//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAF.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAF_USUARIO
    {
        public int CODUSU { get; set; }
        public string NOMUSU { get; set; }
        public string PASUSU { get; set; }
        public string NOMPERUSU { get; set; }
        public string APEPERUSU { get; set; }
        public string DNIUSU { get; set; }
        public Nullable<int> TIPCARUSU { get; set; }
        public Nullable<System.DateTime> FECREG { get; set; }
        public Nullable<System.DateTime> FECMOD { get; set; }
        public string USUREG { get; set; }
        public string USUMOD { get; set; }
        public string ESTREG { get; set; }
    }
}
