//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAF.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAF_DOCUMENTO
    {
        public SAF_DOCUMENTO()
        {
            this.SAF_FLUJO_DOCUMENTO = new HashSet<SAF_FLUJO_DOCUMENTO>();
        }
    
        public int CODDOC { get; set; }
        public Nullable<int> TIPFORDOC { get; set; }
        public Nullable<int> CODFORDOC { get; set; }
        public Nullable<System.DateTime> FECREG { get; set; }
        public Nullable<System.DateTime> FECMOD { get; set; }
        public string USUREG { get; set; }
        public string USUMOD { get; set; }
        public string ESTREG { get; set; }
        public string NOMFORDOC { get; set; }
    
        public virtual ICollection<SAF_FLUJO_DOCUMENTO> SAF_FLUJO_DOCUMENTO { get; set; }
    }
}
