//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAF.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_SAF_PROPUESTAEJECUCION
    {
        public int CODPRO { get; set; }
        public int CODAUD { get; set; }
        public string PERAUD { get; set; }
        public Nullable<int> CODSOA { get; set; }
        public int CODPUB { get; set; }
        public string DESBAS { get; set; }
    }
}
