//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAF.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_SAF_PUBLICACION
    {
        public int CODPUB { get; set; }
        public string NUMPUB { get; set; }
        public Nullable<System.DateTime> FECMAXCRECON { get; set; }
        public int CODBAS { get; set; }
        public string DESBAS { get; set; }
        public Nullable<System.DateTime> FECMAXCONS { get; set; }
        public Nullable<System.DateTime> FECMAXRESCONS { get; set; }
        public Nullable<System.DateTime> FECMAXPREPROP { get; set; }
        public Nullable<int> ESTPUB { get; set; }
        public string NOMPAR { get; set; }
        public Nullable<System.DateTime> FECREG { get; set; }
        public Nullable<System.DateTime> FECMOD { get; set; }
        public string USUREG { get; set; }
        public string USUMOD { get; set; }
        public string ESTREG { get; set; }
    }
}
